# Generated by Django 4.2 on 2023-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cpf', models.TextField(max_length=16)),
                ('email', models.TextField(max_length=100)),
                ('endereco', models.TextField(max_length=255)),
                ('fone', models.TextField(max_length=20)),
            ],
        ),
    ]
